openapi: 3.0.0
info:
  title: API de Acompanhamento Clínico Veterinário
  version: 1.0.0
  description: API para registro e acompanhamento do quadro clínico de pacientes em uma clínica veterinária.
servers:
  - url: http://localhost:3000
paths:
  /pacientes:
    post:
      summary: Registrar um novo paciente
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nome:
                  type: string
                especie:
                  type: string
                raca:
                  type: string
                idade:
                  type: integer
                dono:
                  type: string
              required:
                - nome
                - especie
                - dono
      responses:
        '201':
          description: Paciente registrado com sucesso
        '400':
          description: Dados inválidos
    get:
      summary: Listar todos os pacientes
      responses:
        '200':
          description: Lista de pacientes
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                    nome:
                      type: string
                    especie:
                      type: string
                    raca:
                      type: string
                    idade:
                      type: integer
                    dono:
                      type: string
  /pacientes/{id}:
    get:
      summary: Buscar um paciente pelo ID
      parameters:
        - name: id
          in: path
          required: true
          description: ID do paciente
          schema:
            type: string
      responses:
        '200':
          description: Paciente encontrado
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  nome:
                    type: string
                  especie:
                    type: string
                  raca:
                    type: string
                  idade:
                    type: integer
                  dono:
                    type: string
        '404':
          description: Paciente não encontrado
  /auth/login:
    post:
      summary: Autenticar um usuário
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                senha:
                  type: string
              required:
                - email
                - senha
      responses:
        '200':
          description: Login bem-sucedido
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        '401':
          description: Credenciais inválidas
components:
  schemas:
    Error:
      type: object
      properties:
        message:
          type: string
        code:
          type: integer
    Paciente:
      type: object
      properties:
        id:
          type: string
        nome:
          type: string
        especie:
          type: string
        raca:
          type: string
        idade:
          type: integer
        dono:
          type: string